load("@rules_java//java:defs.bzl", "java_binary")

java_binary(
    name = "hello_world",
    srcs = ["src/com/github/racosta/hello_world/HelloWorld.java"],
    main_class = "com.github.racosta.hello_world.HelloWorld",
    deps = ["//projects/java/greeter"],
)
