load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "pistache",
    hdrs = ["pistache.h"],
    visibility = ["//visibility:public"],
    deps = [
        "@fmt",
        "@pistache",
    ],
)
