load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "player_lib",
    srcs = ["player.go"],
    importpath = "github.com/racosta/monorepo/projects/go/learn_go_with_tests/http_server/internal/player",
    visibility = ["//projects/go/learn_go_with_tests/http_server:__subpackages__"],
)
