load("@rules_perl//perl:perl.bzl", "perl_binary", "perl_test")

perl_binary(
    name = "hello_world",
    srcs = ["hello_world.pl"],
)

perl_test(
    name = "hello_world_test",
    srcs = ["hello_world_test.t"],
)
