load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "common",
    srcs = ["src/lib.rs"],
    edition = "2021",
    visibility = ["//projects/rust/one_hundred_exercises:__subpackages__"],
)
